name: openpanel_flutter
description: "Non official Flutter SDK for openpanel.dev"
version: 0.0.1
homepage: github.com/stevenosse/openpanel_flutter.git

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  
  package_info_plus: ^8.0.0
  mason_logger: ^0.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
